@startuml
title Алгоритм DFS (Рекурсивний обхід)

start
:Позначити поточну вершину як відвідану (visited);
:Вивести назву міста;

while (є суміжна вершина 'to' у списку adj[current]?) is (так)
  if (вершина 'to' ще не відвідана?) then (так)
    :Рекурсивний виклик DFS(to);
  else (ні)
  endif
endwhile

stop
@enduml